services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-backend-standalone
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: ".docker.env"
    volumes:
      - ../src/huggingface_models:/huggingface_models
    networks:
      - rag-net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-backend
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ../src/qdrant_data:/qdrant/storage
    env_file: ".docker.env"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rag-net

  minio:
    image: minio/minio:latest
    container_name: minio-backend
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: ".docker.env"
    command: server /data --console-address ":9001"
    volumes:
      - ../src/minio_data:/data
    networks:
      - rag-net

networks:
  rag-net:
    driver: bridge

volumes:
  qdrant_data:
    driver: local